### ISSUE TITLE
Any Windows builds, please?

### ISSUE THREAD

**Issue by redgpu** [shady-gang/shady#20]
I will try to compile it myself right now, vcc that is, but if you have precompiled binaries, could you share them please? Thank you!

Edited: I compiled it! Here are my pre-compiled binaries for Windows 10 (rename `.7z.zip` to just `.7z`):
[VulkanClangCompiler.7z.zip](https://github.com/Hugobros3/shady/files/13906700/VulkanClangCompiler.7z.zip)
[VulkanClangCompiler_ClangBinary.7z.zip](https://github.com/Hugobros3/shady/files/13930950/VulkanClangCompiler_ClangBinary.7z.zip)
Alternative Dropbox download link:
https://www.dropbox.com/scl/fo/y20s0id7j7xhsaflttnue/h?rlkey=1aeiayswnn35q567y4fmxwyhq&dl=0

**Comment by Hugobros3** [comment]
Hi, Windows builds are planned for the Vulkanised conference in February.

Shady/Vcc consumes normal CMake dependencies.

For SPIRV-Headers you need to install it somewhere and if it's not the default location you need to use `-DSPIRV-Headers_DIR=<path>` to point CMake at the relevant cmakeConfig.cmake file.

**Comment by Hugobros3** [comment]
Note: you can use both msvc and mingw-w64 to build Vcc/Shady on windows. If you're more comfortable with unix-like environments I can recommend msys2.

**Comment by Hugobros3** [comment]
You can look at the CI pipelines for reference. Currently CI only builds Shady and not Vcc since I don't have an easy solution to get LLVM binaries on Windows (the official releases sadly strip the relevant cmake files).

**Comment by pixelcluster** [comment]
Did you install the Vulkan SDK? That should, AFAIK, provide the Vulkan::Headers target (which is missing here).

**Comment by pixelcluster** [comment]
In CMake, that's actually correct. "linking a library" in CMake refers to both adding include paths and adding libraries to link. Vulkan::Headers is a special type of library that only contains headers. "Linking" this library in CMake will therefore only add the proper include paths to include Vulkan headers.

**Comment by Hugobros3** [comment]
You have to install (install directory can be arbitrary) dependencies for their cmakeConfig.cmake files to be correctly placed/edited wrt paths. Alternatively you can use the prebuild librairies from the msys2 environment. WSL is also an option.

**Comment by Hugobros3** [comment]
aobench is an older test that actually uses a different path (parsing OpenCL C++ as OpenCL spir-v), no vcc. the vcc version of aobench lives elsewhere, i'll probably bring it as a Vcc sample later

**Comment by Hugobros3** [comment]
Closing per https://github.com/shady-gang/shady/commit/16f422c62ce063ca4124b6dcc155f0dd142a2d26

I'm aware of the desire for prebuilt windows binaries, but another issue should be opened since this one is quite noisy now
