### ISSUE TITLE
aobench crash

### ISSUE THREAD

**Issue by ib00** [shady-gang/shady#26]
Cool project!

I am trying to run aobench sample and I get a segmentation fault on linux.
(two Vulkan devices: AMD Radeon Graphics (RADV RENOIR), and NVIDIA GeForce RTX 3050 Laptop GPU)

There are several messages before the crash:
'LEA used on a pointer to a non-array type!'

**Comment by Hugobros3** [comment]
Hi, this isn't sufficient information to reproduce/diagnose. The message you got is just an unrelated warning, you can safely ignore it,

**Comment by ib00** [comment]
Thanks for your reply. 

I ran it in debug mode The crash happens in nvidia driver:

Thread 1 "aobench_host" received signal SIGSEGV, Segmentation fault.
0x00007fffd7385162 in ?? () from /usr/lib/libnvidia-glvkspirv.so.535.113.01

Stack trace (omitting stuff from nvidia drivers):

#15 0x00007fffd6216567 in DispatchCreateComputePipelines (
    device=0x555556a9bed0, pipelineCache=0x0, createInfoCount=<optimized out>, 
    pCreateInfos=0x7fffffffd720, pAllocator=0x0, pPipelines=0x555556eccf38)
    at /usr/src/debug/vulkan-validation-layers/Vulkan-ValidationLayers-sdk-1.3.261.1/layers/layer_chassis_dispatch_manual.cpp:1552
#16 0x00007fffd60f4567 in vulkan_layer_chassis::CreateComputePipelines (
    device=0x555556a9bed0, pipelineCache=0x0, createInfoCount=1, 
--Type <RET> for more, q to quit, c to continue without paging--
    pCreateInfos=0x7fffffffd720, pAllocator=0x0, pPipelines=0x555556eccf38)
    at /usr/src/debug/vulkan-validation-layers/Vulkan-ValidationLayers-sdk-1.3.261.1/layers/vulkan/generated/chassis.cpp:656
#17 0x00007ffff7f4433a in create_vk_pipeline ()
   from /tmp/shady/build/lib/libshady_runtime.so



If I run the aobench on AMD (integrated) card, it crashes in:

Thread 1 "aobench_host" received signal SIGSEGV, Segmentation fault.
0x00007fffe74f5b60 in ?? () from /usr/lib/libvulkan_radeon.so

#0  0x00007fffe74f5b60 in ?? () from /usr/lib/libvulkan_radeon.so
#1  0x00007fffe74baaa1 in ?? () from /usr/lib/libvulkan_radeon.so
#2  0x00007fffe74bb34a in ?? () from /usr/lib/libvulkan_radeon.so
#3  0x00007fffe74bb4b6 in ?? () from /usr/lib/libvulkan_radeon.so
#4  0x00007fffd6216567 in DispatchCreateComputePipelines (
    device=0x555556a7ec90, pipelineCache=0x0, createInfoCount=<optimized out>, 
    pCreateInfos=0x7fffffffd740, pAllocator=0x0, pPipelines=0x5555571fee88)
    at /usr/src/debug/vulkan-validation-layers/Vulkan-ValidationLayers-sdk-1.3.261.1/layers/layer_chassis_dispatch_manual.cpp:1552
#5  0x00007fffd60f4567 in vulkan_layer_chassis::CreateComputePipelines (
    device=0x555556a7ec90, pipelineCache=0x0, createInfoCount=1, 
    pCreateInfos=0x7fffffffd740, pAllocator=0x0, pPipelines=0x5555571fee88)
    at /usr/src/debug/vulkan-validation-layers/Vulkan-ValidationLayers-sdk-1.3.261.1/layers/vulkan/generated/chassis.cpp:656
#6  0x00007ffff7f4433a in create_vk_pipeline ()
   from /tmp/shady/build/lib/libshady_runtime.so

**Comment by ib00** [comment]
I can report that this crash went away with one of the commits (fd8acfd, 14e6287). Thanks!

**Comment by Hugobros3** [comment]
Cool! I still need to port aobench to the vcc path though ^^'
