### ISSUE TITLE
ispc broken?

### ISSUE THREAD

**Issue by ib00** [shady-gang/shady#31]
ispc code generator seems to be broken for a while now.

It looks like the code emission produces many errors like in a aobench sample:

/tmp/shady/build/samples/aobench/aobench.ispc:25:43: Error: 
        "uniform" qualifier is illegal with "void" type. 
export void (aobench_kernel)(uniform void * uniform _30);
                                          ^^^^^^^^^

**Comment by Hugobros3** [comment]
This should be fixed on master
